# Generated by Django 2.0.1 on 2018-02-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Climate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATE', models.DateField()),
                ('TMAX', models.FloatField(blank=True, default=None, null=True)),
                ('TMIN', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
    ]
