# Generated by Django 2.0.1 on 2018-02-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climate',
            name='DATE',
            field=models.TextField(),
        ),
    ]
